### ISSUE TITLE
Add review functionality

### ISSUE THREAD

**Issue by simonk21** [upcs/cs341-project-ss2020-rust#81]
Need to add further enhancement to review page, doesn't display user reviews on other pages. 
Possibly add review comments

**Comment by bunger20** [comment]
Maybe this is just because the review section is a work in progress, but when I try to submit a review, I just get this alert:
<img width="902" alt="Screen Shot 2020-04-02 at 10 50 13 AM" src="https://user-images.githubusercontent.com/45083922/78281696-e9ee9200-74cf-11ea-8f2d-82f4fcdc2fed.png">

What is this alert supposed to notify the user of?

**Comment by simonk21** [comment]
> Maybe this is just because the review section is a work in progress, but when I try to submit a review, I just get this alert:
> <img alt="Screen Shot 2020-04-02 at 10 50 13 AM" width="902" src="https://user-images.githubusercontent.com/45083922/78281696-e9ee9200-74cf-11ea-8f2d-82f4fcdc2fed.png">
> 
> What is this alert supposed to notify the user of?

Yes, it was for testing purposes. I have removed the alert. Thank you.
